name: Generate Snake

on:
  schedule: # Runs at 05:00 UTC every day
    - cron: "0 5 * * *"
  push: # Triggers the workflow on push events to the main branch
    branches:
      - main
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/snake.svg

      - name: Commit and push the Snake
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add dist/snake.svg
          git commit -m 'Generate Snake'
          git push
